### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by m0100434** [sam016/Songs-Dup#2]
Hi @sam016 , 

Trying to use this app to clean up a folder that has an bunch of duplicate songs with different files names but identical metadata.  

However, I am not succeeding. Steps taken: 
1 -  I have python 3 installed.  OK
2 - I installed the pytaglib package but received an error message 
ERROR: Command errored out with exit status 1: 'C:\Users\maart\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\maart\\AppData\\Local\\Temp\\pip-install-sv_qf0pu\\pytaglib\\setup.py'"'"'; __file__='"'"'C:\\Users\\maart\\AppData\\Local\\Temp\\pip-install-sv_qf0pu\\pytaglib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\maart\AppData\Local\Temp\pip-record-304cn341\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\maart\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Include\pytaglib' Check the logs for full command output.

3 - When I run the command line anyway, it also errors: 

rmdupsongs.py:99: SyntaxWarning: "is" with a literal. Did you mean "=="?
  ind_sel = 0 if ind_sel is '' else ind_sel
rmdupsongs.py:106: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ind_sel is 0:
Traceback (most recent call last):
  File "rmdupsongs.py", line 190, in <module>
    main()
  File "rmdupsongs.py", line 39, in main
    str_rubbish = ('|'.join(('(' + re.escape(item) + ')') for item in params.rubbish))
TypeError: 'NoneType' object is not iterable

Any advice you can give me to make this run? 

Thanks, 
Maarten

**Comment by sam016** [comment]
@m0100434 it has been so long since I cleaned my directory and used the script again. I will surely check this out.

**Comment by sam016** [comment]
@m0100434 I made some changes for it to work for python3. I have tested it with python3.8.
`pytablib` has its own dependencies to be built and installed. Please refer to this: https://github.com/supermihi/pytaglib#installation-notes

**Comment by m0100434** [comment]
Hi @sam016 , 
Thanks for the update!  The program runs and is asking me to choose the version I would like to keep, so far so good. 

However,  there is an error while removing.  Perhaps I need to run the program as admin?  Any idea how to fix this? 

97/107 - ←[01mtwenty one pilots||Hometown:2←[00m

←[01;91m    0 - Skip (Default) ←[00m
   ←[01;94m 1←[00m - /12 - Hometown.mp3
   ←[01;94m 2←[00m - /W0717560.mp3

Choose which file to keep [1 - 2]:
> 1
Error while removing the file.

**Comment by sam016** [comment]
@m0100434 gotta check.
